### ISSUE TITLE
Pausing, editing the time, and resuming could update the duration to reflect new time

### ISSUE THREAD

**Issue by benrellick** [walmik/timer.jquery#43]
Hi! I'm having a lot of fun working with this, and it's doing 99% of what I need to do, so thanks for making such a solid plugin! One thing I noticed is that callbacks don't work as I expected them to when the time is edited. For example, if the timer's at 8 seconds and I have a 1s duration, but then I pause it and set the time to 6 seconds, the callback doesn't execute until we hit 9 seconds, instead of now executing at 7 seconds as I thought it might after editing the time.

I got around that by adding the following after lines 105, 110, and 114 under makeEditable() in order to reset the duration relative to totalSeconds every time the time is edited.

if (options.duration) {
duration = options.duration = timeToSeconds(options.duration);
// Sets the duration to be that distance from the new edited time
duration = totalSeconds + duration;
}

I guess if you set a single 5 minute timer, you'd probably want to have it go off at 5 min even if you edited the time leading up to that, but for a short term repeating duration it probably makes sense to reset it each time. I don't have the skills to add that distinction in as an option, but I just thought I'd mention what I came across

**Comment by walmik** [comment]
Hello Ben, 

Thank you very much for your kind words of appreciation and for raising this issue! I will look into it and apply a fix accordingly.

**Comment by walmik** [comment]
This issue is fixed in v0.4.3. Thanks for pointing it out @benrellick Lemme know if it works as expected. Here is the change that is implemented in this fix:

If a user sets a duration of 5 seconds (such that some functionality every 5 seconds), then the timer will always call the functionality (defined in callback) in multiples of 5 regardless of where the timer was started from. So if the timer was started at 8 seconds then the first callback will happen when the timer displays **10 sec**. If user edits the time and sets it to 3s, then the next callback will happen when the timer displays **5 sec**
