### ISSUE TITLE
CountDown timer

### ISSUE THREAD

**Issue by almasn86** [walmik/timer.jquery#54]
is there any possibility to make countdown of timer?

**Comment by shacow** [comment]
You can use the Timed Events

Start a timer and execute a function after a certain duration. You can use this to simulate a timed event.

//start a timer & execute a function in 5 minutes & 30 seconds
$('#div-id').timer({
    duration: '5m30s',
    callback: function() {
        alert('Time up!');
    }
});

**Comment by walmik** [comment]
Thanks @shacow :)

Hi @almasn86 in case you had meant like a reverse timer, then the following will start a timer in a div with id timer and it countdown from 5 minutes and go on to 0 seconds:

```
$('#timer').timer({
    countdown: true,
    duration: '5m'
});
```

You can change the `5m` to `5s` to start at 5 seconds instead of 5 minutes. Either ways, once the timer reaches 0 seconds, it will show an alert box by default. You can override this by passing a custom callback to the plugin:

```
$('#timer').timer({
    countdown: true,
    duration: '5s',
    callback: function() {
        console.log('done');
    }
});
```

This will output `done` in the console after counting down 5 seconds. Hope this helps!
